# Generated by Django 2.2 on 2023-01-08 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=100, verbose_name='Contact Name')),
                ('contact_status', models.BooleanField(default=True, verbose_name='Contact Status')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_type', models.IntegerField(choices=[(2, 'Work'), (3, 'Other'), (1, 'Home')], default=1)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('contact_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_phone', to='Contact.Contact', verbose_name='Contact')),
            ],
        ),
    ]
