# Generated by Django 2.2 on 2023-01-08 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='contact_status',
        ),
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_type',
            field=models.IntegerField(choices=[(1, 'Home'), (2, 'Work'), (3, 'Other')], default=1),
        ),
    ]
