# Generated by Django 2.2 on 2023-01-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Contact', '0002_auto_20230108_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='phone_type',
        ),
    ]
